version: '3'
services:
  live-server:
    image: nwndotnet/anvil:8193.35.1
    hostname: nwserver
    container_name: live-server
    stop_signal: SIGINT
    env_file:
      - ${PWD-.}/config/prod.env
      - ${PWD-.}/config/db.env
    stdin_open: true
    tty: true
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0
      - ${PWD-.}/server/:/nwn/home
    restart: unless-stopped
    ports:
      - "5121:5121/udp"

  test-server:
    image: nwndotnet/anvil:8193.35.1
    hostname: nwserver
    container_name: live-server
    stop_signal: SIGINT
    env_file:
      - ${PWD-.}/config/test.env
      - ${PWD-.}/config/db.env
    stdin_open: true
    tty: true
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0
      - ${PWD-.}/server/:/nwn/home
    restart: unless-stopped
    ports:
      - "5121:5121/udp"

  nwsync:
    hostname: nwsyncnginx
    stop_signal: SIGINT
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ${PWD-.}/nwsync/data/:/usr/share/nginx/html:ro
      - ${PWD-.}/nwsync/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  nwsync-test:
    hostname: nwsyncnginx-test
    stop_signal: SIGINT
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ${PWD-.}/nwsync_test/data/:/usr/share/nginx/html:ro
      - ${PWD-.}/nwsync_test/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  webui:
    hostname: webui
    stop_signal: SIGINT
    build: ./webui
    ports:
      - "8000:8000"
    environment:
      - appusername=amiadm
      - password=Ilikenewareas!1
    volumes:
      - ${PWD-.}/server/development/:/app/uploads
    restart: unless-stopped

  database:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - ${PWD-.}/config/db.env
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - ${PWD-.}/config/db.env
    ports:
      - "5050:80"