services:
  dev:
    image: nwndotnet/anvil:8193.37.2
    network_mode: host
    hostname: nwserver
    container_name: live-server
    stop_signal: SIGINT
    env_file:
      - ${PWD-.}/config/dev.env
      - ${PWD-.}/config/db.env
    stdin_open: true
    tty: true
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0
      - ${PWD-.}:/nwn/home
    restart: unless-stopped

  database:
    image: postgres
    # network_mode: host
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ${PWD-.}/config/db.env
    volumes:
      - ${PWD-.}/pgdata-dev:/var/lib/postgresql/data

  enginedb:
    image: postgres
    # network_mode: host
    container_name: enginedb
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ${PWD-.}/config/enginedb.env
    volumes:
      - ${PWD-.}/pgdata-engine-dev:/var/lib/postgresql/data
