version: '3'
services:
  nwserver:
    image: nwndotnet/anvil:8193.34.19
    hostname: nwserver
    container_name: live-server
    stop_signal: SIGINT
    env_file: ${PWD-.}/config/nwserver.env
    stdin_open: true
    tty: true
    volumes:
      - ${PWD-.}/logs:/nwn/run/logs.0
      - ${PWD-.}/server/:/nwn/home
    restart: unless-stopped
    ports:
      - "5121:5121/udp"
  database:
    image: postgres
    restart: always
    env_file:
      - ${PWD-.}/config/db.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080